package v8serde

import (
	"encoding/hex"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

// fixtures generated by: node -e "fs.writeFileSync('f_<name>.bin', v8.serialize(<value>))"
// regenerate with the script in history/electron-churning-repro/README.md.
const fixtureDir = "/tmp/v8fixtures"

type fixtureCase struct {
	file string
	want any
}

func fixtureCases() []fixtureCase {
	return []fixtureCase{
		{"f_null.bin", nil},
		{"f_true.bin", true},
		{"f_false.bin", false},
		{"f_undef.bin", nil},
		{"f_int.bin", float64(42)},
		{"f_negint.bin", float64(-7)},
		{"f_double.bin", float64(3.5)},
		{"f_str_ascii.bin", "hello"},
		{"f_str_utf8.bin", "你好"},
		{"f_arr.bin", []any{float64(1), "two", true}},
		{"f_obj_flat.bin", map[string]any{
			"type": "http", "method": "POST", "url": "/wails/runtime", "count": float64(5),
		}},
		{"f_obj_nested.bin", map[string]any{
			"object": float64(0), "method": float64(0),
			"args": map[string]any{
				"a": float64(1), "b": "x",
				"c": []any{float64(1), float64(2), float64(3)},
			},
			"callid": "abc",
		}},
		{"f_u8.bin", []byte{1, 2, 3, 255, 0}},
	}
}

func TestDeserializeFixtures(t *testing.T) {
	for _, fc := range fixtureCases() {
		t.Run(fc.file, func(t *testing.T) {
			data, err := os.ReadFile(filepath.Join(fixtureDir, fc.file))
			if err != nil {
				t.Skipf("fixture missing: %v", err)
			}
			got, err := Deserialize(data)
			if err != nil {
				t.Fatalf("Deserialize: %v", err)
			}
			if !reflect.DeepEqual(got, fc.want) {
				t.Fatalf("mismatch:\n got %#v\nwant %#v", got, fc.want)
			}
		})
	}
}

func TestRoundTrip(t *testing.T) {
	cases := []any{
		nil, true, false,
		float64(42), float64(-7), float64(3.5),
		"hello", "你好",
		[]byte{1, 2, 3, 255, 0},
		[]any{float64(1), "two", true},
		map[string]any{"type": "http", "count": float64(5)},
		map[string]any{"args": map[string]any{"a": float64(1), "b": "x"}},
	}
	for _, want := range cases {
		data, err := Serialize(want)
		if err != nil {
			t.Fatalf("Serialize(%#v): %v", want, err)
		}
		got, err := Deserialize(data)
		if err != nil {
			t.Fatalf("Deserialize(%#v): %v", want, err)
		}
		if !reflect.DeepEqual(got, want) {
			t.Fatalf("roundtrip mismatch:\n got %#v\nwant %#v", got, want)
		}
	}
}

func TestCrossCheckWithNode(t *testing.T) {
	// Byte-exact pins against Node's v8.serialize output (Node 25 golden
	// bytes). These caught two real bugs: kEndJSObject's trailing varint
	// is the PROPERTY COUNT (we wrote an object id) and kEndDenseJSArray's
	// trailing varint is the ELEMENT COUNT. Node's deserializer validates
	// both and rejected our objects wholesale ("invalid or unsupported
	// version" / "Unable to deserialize cloned data").
	cases := []struct {
		name string
		val  any
		want string
	}{
		{"one-prop map", map[string]any{"a": float64(1)}, "ff0f6f22016149027b01"},
		{"dense array", []any{float64(1), float64(2), float64(3)}, "ff0f4103490249044906240003"},
		{"uint8 array", map[string]any{"d": []byte{1, 2, 3}}, "ff0f6f2201645c01030102037b01"},
		// padding regression: a two-byte string after an odd-offset
		// one-byte string carries V8's kPadding (0x00) — this exact frame
		// is what the IME leg's value RPC produces
		{"padding before two-byte", []any{"value", "中文输入"},
			"ff0f4102220576616c75650063082d4e8765938f6551240002"},
	}
	for _, tc := range cases {
		data, err := Serialize(tc.val)
		if err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		if got := hex.EncodeToString(data); got != tc.want {
			t.Errorf("%s:\n got %s\nwant %s", tc.name, got, tc.want)
		}
	}
}
